name: Generate Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anuraghazra/github-readme-stats-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_branch: stats-output
